version: "3"

services:
  api:
    build: ./api
    container_name: node-api
    environment:
      PORT: 5000
    networks:
      - app
    ports:
      - "5000:5000"
  ui:
    build: ./ui
    networks:
      - app
    ports:
      - "3000:3000"
networks:
  app:
